config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: :new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :body, presence: true, length: { minimum: 6 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { username.downcase! }

  has_many :articles
  validates :username, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false}
  validates :password, presence: true
  validates :password_confirmation, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    # Temporary assign a user to prevent error
    @article.user = User.find(2)
    if @article.save
      redirect_to @article, notice: 'Article was created successfully'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path, notice: 'Article was deleted successfully'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])    
  end

  def article_params
    params.require(:article).permit(:name, :body, :image_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @articles = Article.all.take(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome #{@user.first_name}, you have successfully signed up"
      redirect_to articles_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation)  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if article.errors.any? %>
  <div class='alert alert-danger alert-dismissible fade show' role='alert'>
    <h2 class='alert-heading'><%= pluralize(article.errors.count, 'error') %> prohibited this article from being saved:</h2>
    <ul>
      <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<%= form_with model: article, id: 'article-form', class: 'mb-3' do |form| %>
  <div class='mb-3'>
    <%= form.label :name, class: 'form-label'%>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter article name' %>
  </div>
  <div class='mb-3'>
    <%= form.label :image_url, 'Image Url', class: 'form-label' %>
    <%= form.text_field :image_url, class: 'form-control', placeholder: 'Enter article image to be displayed' %>
  </div>
  <div class='mb-3'>
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control', placeholder: 'Enter article'%>
  </div>
  <div class='mt-5'>
    <%= link_to 'Back', articles_path, class: 'btn btn-danger col-3' %>
    <%= form.submit class: 'btn btn-primary col-3 me-3' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<nav class="bg-dark navbar navbar-dark navbar-expand-lg sticky-top w-100">
  <%= render 'shared/navigation' %>
</nav>
<section class='container-fluid px-5 mt-5'>
  <h1>Edit article</h1>
  <%= render 'form', article: @article %>
</section>

app/views/articles/index.html.erb
<nav class="bg-dark navbar navbar-dark navbar-expand-lg sticky-top w-100">
  <%= render 'shared/navigation' %>
</nav>
<section class='p-3' id='articles-list'>
  <div class='d-flex'>
    <h1>Articles</h1>
    <%= link_to 'New Article', new_article_path, class: 'align-self-center btn btn-primary ms-5 px-5 py-2 rounded-pill shadow' %>
  </div>
  <div class="card-group">
    <% @articles.each do |article| %>
      <div class="card m-2 border flex-wrap">
        <% if article.image_url %>
          <%= image_tag article.image_url, class: 'card-img-top' %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= article.name %></h5>
          <p class="card-text"><%= truncate(article.body, length: 200) %> </p>
          <div class='card-text'>
            <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-primary btn-sm col-5' %>
            <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm col-5' %>
          </div>
        </div>
        <div class="card-footer bg-white border-top-0">
          <small class="text-muted">Last updated <%= time_ago_in_words(article.updated_at) %></small>
        </div>
      </div>
    <% end %>
  </div>

app/views/articles/new.html.erb
<nav class="bg-dark navbar navbar-dark navbar-expand-lg sticky-top w-100">
  <%= render 'shared/navigation' %>
</nav>
<section class='container-fluid px-5 mt-5'>
  <h1>Create new article</h1>
  <%= render 'form', article: @article %>
</section>

app/views/articles/show.html.erb
<nav class="bg-dark navbar navbar-dark navbar-expand-lg sticky-top w-100">
  <%= render 'shared/navigation' %>
</nav>
<article class='container-fluid p-0 min-h-25'>
  <header id='article-title' class='align-items-center d-flex flex-column justify-content-center' style= "background-image: url(<%= @article.image_url%>)">
    <span class="badge rounded-pill bg-light text-dark px-4 py-2">Productivity</span>
    <h1 class='fw-bolder text-white text-center text-shadow my-3'><%= @article.name %></h1>
    <p class='text-white text-shadow text-uppercase fspace-1'>James Clear</p>
  </header>
  <section class='flex-grow-1 container-fluid p-4'>
    <div class='row'>
      <div class='col-md-8 ps-3 pt-3'><%= simple_format(@article.body) %></div>
      <div class='col-md-4'>
        <h2>Comments (26)</h2>
        <button type='button' class='btn btn-secondary w-100 text-white' role='button'>Add Comment</button>
        <form action="" class='py-3' id='commentsForm'>
          <div class="form-floating mb-3">
            <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Enter your name</label>
          </div>
          <div class="form-floating">
            <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea"></textarea>
            <label for="floatingTextarea">Enter your comment</label>
          </div>
          <button type="submit" class='btn btn-dark mt-3'>Submit</button>
        </form>
        <ul class='list-group list-group-flush'>
          <li class='list-group-item p-2'>
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 fw-bolder">Anna Gabriel</h5>
                <small class='text-muted'>3 days ago</small>
              </div>
            <p class='mb-1'>You always give good advice. What would you say to someone?</p>
          </li>
          <li class='list-group-item p-2'>
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 fw-bolder">Anna Gabriel</h5>
                <small class='text-muted'>3 days ago</small>
              </div>
            <p class='mb-1'>You always give good advice. What would you say to someone?</p>
          </li>
        </ul>
      </div>
    </div>
  </section>
</article>

app/views/layouts/_footer.html.erb
<footer class="bg-dark py-4 text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to 'Anna Gabriel', 'https://github.com/annagabriel-hash/', class: 'text-white', id: 'copyright' %></small>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<nav class="bg-dark navbar navbar-dark navbar-expand-lg opacity-50 position-absolute w-100">
  <%= render 'shared/navigation' %>
</nav>
<section id="homepage" class="carousel slide carousel-fade h-100" data-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#homepage" data-bs-slide-to="0" class="active"></button>
    <button type="button" data-bs-target="#homepage" data-bs-slide-to="1"></button>
    <button type="button" data-bs-target="#homepage" data-bs-slide-to="2"></button>
  </div>
  <div class="carousel-inner">
    <% @articles.each.with_index do |article, i| %>
    <div class="carousel-item <%= 'active' if i == 0 %>">
      <%= image_tag article.image_url, class: 'd-block w-100 h-auto' %>
      <div class="carousel-caption d-block">
        <h3 class='fs-1 text-shadow'><%= article.name %></h3>
        <%= link_to 'Read more', article, class: 'btn btn-light'%>
      </div>
    </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#homepage" data-bs-slide="prev">
    <span class="carousel-control-prev-icon"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#homepage" data-bs-slide="next">
    <span class="carousel-control-next-icon"></span>
  </button>
</section>

app/views/shared/_navigation.html.erb
<div class="container-fluid position-relative">
	<%= link_to 'Blog', root_path, class: 'navbar-brand' %>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id='navbarSupportedContent'>
		<ul class="navbar-nav me-auto mb-2 mb-lg-0 flex-grow-1 justify-content-around">
			<li class="nav-item"><a class="nav-link text-uppercase text-white" href="#">Travel</a></li>
			<li class="nav-item"><a class="nav-link text-uppercase text-white" href="#">Productivity</a></li>
			<li class="nav-item"><a class="nav-link text-uppercase text-white" href="#">Coding</a></li>
		</ul>
		<div>
			<div class="dropdown d-none">
				<a class="btn btn-outline-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" data-bs-display="static">
					anna_gabriel 
				</a>
				<ul class="dropdown-menu dropdown-menu-dark dropdown-menu-lg-end">
					<li><%= link_to 'Create Article', new_article_path, class: 'dropdown-item'%></li>
					<li><%= link_to 'View Articles', articles_path, class: 'dropdown-item'%></li>
					<li><%= link_to 'Logout', articles_path, class: 'dropdown-item'%></li>
				</ul>
			</div>
			<%= link_to 'Login / Signup', signup_path, class: 'btn btn-outline-light' %>
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<% if user.errors.any? %>
  <div class='alert alert-danger alert-dismissible fade show' role='alert'>
    <h2 class='alert-heading'><%= pluralize(user.errors.count, 'error') %> prohibited this user from being saved:</h2>
    <ul>
      <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<%= form_with model: user, id: 'user-form', class: 'mb-3' do |form| %>
  <div class='mb-3'>
    <%= form.label :username, class: 'form-label'%>
    <%= form.text_field :username, class: 'form-control', placeholder: 'Enter username' %>
  </div>
  <div class='mb-3'>
    <%= form.label :first_name, class: 'form-label' %>
    <%= form.text_field :first_name, class: 'form-control', placeholder: 'Enter firstname' %>
  </div>
  <div class='mb-3'>
    <%= form.label :last_name, class: 'form-label' %>
    <%= form.text_field :last_name, class: 'form-control', placeholder: 'Enter lastname'%>
  </div>
  <div class='mb-3'>
    <%= form.label :email, class: 'form-label' %>
    <%= form.text_field :email, class: 'form-control', placeholder: 'Enter email'%>
  </div>
  <div class='mb-3'>
    <%= form.label :password, class: 'form-label' %>
    <%= form.password_field :password, class: 'form-control', placeholder: 'Enter password'%>
  </div>
  <div class='mb-3'>
    <%= form.label :password_confirmation, class: 'form-label' %>
    <%= form.password_field :password_confirmation, class: 'form-control', placeholder: 'Reenter password'%>
  </div>
  <div class='mt-5 row flex-nowrap px-2'>
    <%= link_to 'Back', root_path, class: 'btn btn-danger flex-shrink-1 me-2' %>
    <%= form.submit class: 'btn btn-primary flex-shrink-1' %>
  </div>
<% end %>

app/views/users/new.html.erb
<nav class="bg-dark navbar navbar-dark navbar-expand-lg sticky-top w-100">
  <%= render 'shared/navigation' %>
</nav>
<section class='container-fluid row m-0 p-0' id='signup'>
  <div class="col-6">
  </div>
  <div class='col-6 p-4'>
    <h1 class='text-center'>Signup</h1>
    <%= render 'form', user: @user %>
  </div>
</section>